### PR TITLE
Fix Android StatusBar Height.

### PR DESCRIPTION
**Pull request by BenQoder**
Fix Android Status Bar Height From 0 to current Height

### CODE REVIEW

**Comment by BenQoder** [comment]
The Preview Below Is Without Current Status Bar Height, You See, There's No Spacing From The Top Bar.
screenshot_1535515420

Now, After Setting Current Height, 
screenshot_1535515319
The Nav Shifts From Status Bar

**Comment by BenQoder** [comment]
I Hope You Are Able To Spot The Differences.

**Comment by gaoxiaosong** [comment]
Maybe you use `StatusBar.setTranslucent` to change the translucent status. I will consider this situation and publish a new version later.

**Comment by gaoxiaosong** [comment]
@BenQoder I have published v1.2.5, and add support for 'translucent' props. You can see README or example project. Thanks for your attention.

**Pull request merged**
